---
output:
  github_document:
    html_preview: false
---

## Setting up the data base

Only requirement: install docker and docker-compose. Follow these tutorials: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04 and https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-20-04

Create folder:

```{bash}
mkdir ~/bicing_experiment
```

Create a folder for the MySQL data. ***REMEMBER TO CHANGE THE MYSQL DATA TO OUTSIDE THE REPO FOLDER FOR SECURITY**.

```{bash}
cd ~/bicing_experiment
touch .gitignore
echo "data/" >> ./.gitignore
echo ".Rhistory" >> ./.gitignore
```

Remember to change both passwords and accounts

```{bash}
mkdir -p ./sql/
echo "
CREATE DATABASE bicing;
CREATE USER 'whatever1'@'%' IDENTIFIED WITH mysql_native_password BY '123';
GRANT ALL ON bicing.* TO 'whatever1'@'%';
CREATE USER 'whatever2'@'localhost' IDENTIFIED WITH mysql_native_password BY '123';
GRANT ALL ON bicing.* TO 'whatever2'@'localhost';

/* Make sure the privileges are installed */
FLUSH PRIVILEGES;

USE bicing;

CREATE TABLE bicing_stations (
   id_hash VARCHAR(30),
   id VARCHAR(30),
   latitude VARCHAR(30),
   longitude VARCHAR(30),
   address VARCHAR(30),
   slots VARCHAR(30),
   empty_slots VARCHAR(30),
   free_bikes VARCHAR(30),
   ebikes VARCHAR(30),
   has_ebikes VARCHAR(30),
   status VARCHAR(30),
   time VARCHAR(30),
   day VARCHAR(30),
   month VARCHAR(30),
   year VARCHAR(30),
   error_msg VARCHAR(30)
);
" >> sql/init_db.sql

```

It creates the data folder automatically. Remember to change password. ****REMEMBER TO CHANGE THE FOLDER OF THE DATA TO OUTSIDE THE REPO FOR SECURITY**.

```{bash}

echo '
version: "3.1"
services:
  db:
    container_name: sql-bicing
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /home/cimentadaj/bicing_experiment/sql:/docker-entrypoint-initdb.d
      - /home/cimentadaj/bicing_experiment/data:/var/lib/mysql
' >> docker-compose.yml

```

```{bash}
docker-compose up -d
```

If you get some errors due to some port already in use this could be due to two reasons. Either you have another container redirecting to that port (use `docker ps` and `docker stop` to stop it) or you have a MySQL instance running locally already serving the port. You can stop it with `sudo service mysql stop`.

And run this

```{bash}
mysql -h 127.0.0.1 -P 3306 -u root -p -e "SHOW DATABASES;"
```

You should see that the bicing database was created. You can also connect from R and extract data:

```{r}
library(DBI)
library(RMySQL)

con <- DBI::dbConnect(MySQL(),
                      host = '127.0.0.1',
                      dbname = 'bicing',
                      port = 3306,
                      user = 'whatever',
                      password = '123')


dbGetQuery(con, "SELECT * FROM bicing.bicing_stations")
```

Next step would be to check that appending data and restarting docker-compose shows the same data again.
